### ISSUE TITLE
Subir la documentación al repositorio

### ISSUE THREAD

**Issue by AlejandroMoncada** [AlejandroMoncada/Dev_group_Programmy#5]

**Comment by JuanPabloRami** [comment]
[Diagrama de Gantt.xlsx](https://github.com/AlejandroMoncada/Dev_group_Programmy/files/7514458/Diagrama.de.Gantt.xlsx)
[EspecificaciónDeRequisitosDeSoftwarev2.0.docx](https://github.com/AlejandroMoncada/Dev_group_Programmy/files/7514459/EspecificacionDeRequisitosDeSoftwarev2.0.docx)
[PlanteamientoDelProblemaV2.docx](https://github.com/AlejandroMoncada/Dev_group_Programmy/files/7514461/PlanteamientoDelProblemaV2.docx)
[PT-ERS-01-EspecificaciónDeRequisitosDeSoftware.docx](https://github.com/AlejandroMoncada/Dev_group_Programmy/files/7514462/PT-ERS-01-EspecificacionDeRequisitosDeSoftware.docx)
[1.PT-PP-01-PlanteamientoDelProblema.docx](https://github.com/AlejandroMoncada/Dev_group_Programmy/files/7514463/1.PT-PP-01-PlanteamientoDelProblema.docx)
